import type { Dictionary } from './en';

const bs: Dictionary = {
  'app.name': 'Knowledge RPG',

  'common.continue': 'Nastavi',
  'common.back': 'Nazad',
  'common.cancel': 'Odustani',
  'common.start': 'Počni',
  'common.done': 'Gotovo',
  'common.check': 'Provjeri',
  'common.retry': 'Pokušaj ponovo',
  'common.locked': 'Zaključano',
  'common.level': 'Nivo {level}',
  'common.sources': 'Izvori',
  'common.scholarsDiffer': 'Učenjaci se razilaze',
  'common.save': 'Sačuvaj',

  'tabs.home': 'Početna',
  'tabs.map': 'Mapa',
  'tabs.quests': 'Zadaci',
  'tabs.profile': 'Junak',

  'onboarding.welcome.title': 'Knowledge RPG',
  'onboarding.welcome.body': 'Tvoj junak jača stvarnim znanjem. Uči, odgovaraj, razumij – i napreduj.',
  'onboarding.language': 'Izaberi jezik',
  'onboarding.hero': 'Napravi svog junaka',
  'onboarding.name': 'Ime tvog junaka',
  'onboarding.namePlaceholder': 'Ime',
  'onboarding.nameError': 'Unesi ime (1–20 znakova).',
  'onboarding.loopTitle': 'Kako napreduješ',
  'onboarding.loop': 'Uči → Odgovori → Razumij → Osvoji XP → Napreduj → Otključaj → Ponovi',
  'onboarding.start': 'Započni avanturu',
  'onboarding.next': 'Dalje',
  'onboarding.step': 'Korak {current} od {total}',

  'character.title': 'Tvoj junak',
  'character.skin': 'Boja kože',
  'character.hair': 'Kosa',
  'character.hairColor': 'Boja kose',
  'character.headwear': 'Pokrivalo za glavu',
  'character.outfit': 'Odjeća',
  'character.outfitColor': 'Boja odjeće',
  'character.accessory': 'Dodatak',
  'character.option': '{group}: {value}',
  'character.hair.short': 'Kratka',
  'character.hair.curly': 'Kovrdžava',
  'character.hair.long': 'Duga',
  'character.hair.buzz': 'Jako kratka',
  'character.hair.bun': 'Punđa',
  'character.headwear.none': 'Bez',
  'character.headwear.kufi': 'Kapica',
  'character.headwear.hijab': 'Hidžab',
  'character.headwear.cap': 'Kačket',
  'character.outfit.thobe': 'Dželabija',
  'character.outfit.hoodie': 'Duks',
  'character.outfit.jacket': 'Jakna',
  'character.outfit.abaya': 'Abaja',
  'character.accessory.none': 'Bez',
  'character.accessory.glasses': 'Naočale',
  'character.accessory.backpack': 'Ranac',
  'character.accessory.scarf': 'Šal',
  'character.accessory.lantern': 'Fenjer',

  'streak.label': 'Niz učenja',
  'streak.days': '{count} dana',
  'streak.day': '{count} dan',
  'streak.today': 'Danas si učio',
  'streak.notToday': 'Završi lekciju, ponavljanje ili izazov da nastaviš niz',
  'streak.note': 'Računa se samo smisleno učenje. Odmori kad god ti treba – učenje nije trka.',

  'home.greeting': 'Es-selamu alejkum, {name}!',
  'home.continue': 'Nastavi učiti',
  'home.allDone': 'Sve jedinice su završene – pokušaj majstorske izazove ili ponavljanje.',
  'home.daily': 'Dnevni izazov',
  'home.dailyDone': 'Završeno danas – sutra stiže novi.',
  'home.quests': 'Današnji zadaci',
  'home.review': 'Pokušajmo ponovo',
  'home.reviewCount': 'Pitanja na redu: {count}',
  'home.reviewNone': 'Trenutno nema ništa za ponavljanje',
  'home.stats': 'Statistika znanja',

  'map.title': 'Mapa svijeta',
  'map.subtitle': 'Svako mjesto je oblast znanja. Završi jedinice da otvoriš sljedeće.',
  'map.locked': 'Završi {count} jedinice u „{area}“ da otključaš',
  'map.mastered': 'Savladano',

  'area.units': 'Jedinice učenja',
  'area.master': 'Majstorski izazov',
  'area.masterBody': '{count} pitanja iz ove oblasti. Za prolaz ti treba {percent} %.',
  'area.masterLocked': 'Prvo završi sve jedinice ove oblasti.',
  'area.masterPassed': 'Položeno · najbolje {score} %',
  'area.knowledge': 'Znanje: {percent} %',
  'area.unitLocked': 'Prvo završi prethodnu jedinicu',
  'area.difficulty': 'Težina {level}/3',
  'area.notFound': 'Ova oblast nije pronađena.',

  'unit.learn': 'Uči',
  'unit.practice': 'Vježbaj',
  'unit.test': 'Test',
  'unit.explanation': 'Zašto je to važno',
  'unit.readAloud': 'Pročitaj naglas',
  'unit.doneReading': 'Razumio sam – vježba',
  'unit.startTest': 'Počni test',
  'unit.finish': 'Preuzmi nagradu',
  'unit.notFound': 'Ova jedinica nije pronađena.',
  'unit.locked': 'Ova jedinica je još zaključana.',
  'unit.exitTitle': 'Napustiti jedinicu?',
  'unit.exitBody': 'Dosadašnji odgovori neće se računati kao završena jedinica.',
  'unit.exit': 'Napusti',
  'unit.stay': 'Ostani',

  'player.correct': 'Tačno!',
  'player.notQuite': 'Ne baš',
  'player.correctAnswer': 'Tačan odgovor: {answer}',
  'player.addedToReview': 'Ovo ćemo kasnije pokušati ponovo.',
  'player.label.practice': 'Vježba – ne boduje se',
  'player.label.test': 'Test',
  'player.label.master': 'Majstorski izazov',
  'player.label.review': 'Pokušajmo ponovo',
  'player.label.daily': 'Dnevni izazov',

  'q.true': 'Tačno',
  'q.false': 'Netačno',
  'q.ordering.hint': 'Dodirni stavke pravilnim redom.',
  'q.ordering.reset': 'Počni ispočetka',
  'q.matching.hint': 'Dodirni stavku lijevo, pa njen par desno.',
  'q.matching.mistakes': 'Greške: {count}',
  'q.memory.hint': 'Okreni dvije karte da pronađeš par.',
  'q.memory.moves': 'Potezi: {count}',
  'q.categorize.hint': 'Dodirni stavku, pa grupu kojoj pripada. Dodirni postavljenu stavku da je vratiš.',
  'q.scenario.title': 'Šta bi ti uradio?',

  'reward.title': 'Jedinica završena!',
  'reward.score': '{correct} od {total} tačno',
  'reward.xp': '+{xp} XP',
  'reward.noXp': 'XP si ovdje već osvojio – ponovna vježba ti ipak pomaže da zapamtiš.',
  'reward.newBadge': 'Novo dostignuće!',
  'reward.next': 'Sljedeća jedinica',
  'reward.area': 'Nazad na oblast',

  'master.title': 'Majstorski izazov',
  'master.intro': '{count} pitanja o oblasti {area}. Postigni {percent} % da savladaš ovu oblast. Ovo je izazov znanja – bez borbe, samo razumijevanje.',
  'master.start': 'Započni izazov',
  'master.passedTitle': 'Oblast savladana!',
  'master.passedBody': 'Postigao si {score} %. Tvoje znanje o oblasti {area} je poraslo.',
  'master.failedTitle': 'Još ne – i to je u redu',
  'master.failedBody': 'Postigao si {score} % (potrebno {percent} %). Ponovi teme ispod, pa pokušaj ponovo.',
  'master.weakTopics': 'Teme za ponavljanje',
  'master.review': 'Ponovi sada',
  'master.retry': 'Pokušaj ponovo',

  'quests.title': 'Knjiga zadataka',
  'quests.subtitle': 'Nekoliko malih zadataka dnevno. Bez tajmera, bez pritiska.',
  'quests.daily': 'Završi današnji dnevni izazov',
  'quests.learning': 'Završi jedinicu „{title}“',
  'quests.knowledge': 'Tačno odgovori na {count} pitanja iz oblasti {area}',
  'quests.review': 'Ponovi {count} pitanja koja si ranije promašio',
  'quests.challenge': 'Položi majstorski izazov oblasti {area}',
  'quests.kind.daily': 'Dnevni zadatak',
  'quests.kind.learning': 'Zadatak učenja',
  'quests.kind.knowledge': 'Zadatak znanja',
  'quests.kind.review': 'Zadatak ponavljanja',
  'quests.kind.challenge': 'Zadatak izazova',
  'quests.done': 'Završeno',
  'quests.achievements': 'Dostignuća',

  'review.title': 'Pokušajmo ponovo',
  'review.intro': 'Promašena pitanja vraćaju se nakon nekog vremena – teže teme prve.',
  'review.start': 'Počni ({count})',
  'review.emptyTitle': 'Trenutno ništa nije na redu',
  'review.emptyBody': 'Promašena pitanja vraćaju se ovdje nakon nekog vremena.',
  'review.next': 'Sljedeće ponavljanje: {date}',
  'review.doneTitle': 'Ponavljanje završeno',
  'review.doneBody': 'Zapamtio si {correct} od {total}.',

  'daily.title': 'Dnevni izazov',
  'daily.kind.question': 'Pitanje',
  'daily.kind.scenario': 'Scenarij',
  'daily.kind.miniGame': 'Mini igra',
  'daily.kind.memory': 'Memorija',
  'daily.kind.review': 'Ponavljanje',
  'daily.doneTitle': 'Dnevni izazov završen!',
  'daily.already': 'Današnji izazov si već završio. Vidimo se sutra!',

  'profile.title': 'Tvoj junak',
  'profile.edit': 'Uredi junaka',
  'profile.xpToNext': 'Još {xp} XP do nivoa {level}',
  'profile.knowledgeMap': 'Mapa znanja',
  'profile.knowledgeNote': 'Udio sadržaja svake oblasti na koji si tačno odgovorio i koji trenutno ne trebaš ponavljati – mjeri naučeno znanje, a ne vjeru.',
  'profile.stats': 'Statistika',
  'profile.settings': 'Postavke',
  'stats.units': 'Završene jedinice',
  'stats.masters': 'Savladane oblasti',
  'stats.answers': 'Tačni odgovori',
  'stats.accuracy': 'Tačnost',
  'stats.longest': 'Najduži niz',
  'stats.reviews': 'Zapamćena ponavljanja',
  'badges.locked': 'Još nije osvojeno',
  'badges.earnedOn': 'Osvojeno {date}',
  'badge.first_lesson.name': 'Prva lekcija',
  'badge.first_lesson.desc': 'Završi svoju prvu jedinicu.',
  'badge.first_perfect_quiz.name': 'Prvi savršeni kviz',
  'badge.first_perfect_quiz.desc': 'Tačno odgovori na sva testna pitanja jedinice.',
  'badge.learner_7.name': 'Učenik 7 dana',
  'badge.learner_7.desc': 'Uči 7 dana zaredom.',
  'badge.learner_30.name': 'Učenik 30 dana',
  'badge.learner_30.desc': 'Uči 30 dana zaredom.',
  'badge.salah_scholar.name': 'Poznavalac namaza',
  'badge.salah_scholar.desc': 'Položi majstorski izazov Doline namaza.',
  'badge.quran_explorer.name': 'Istraživač Kur\'ana',
  'badge.quran_explorer.desc': 'Položi majstorski izazov Biblioteke Kur\'ana.',
  'badge.seerah_explorer.name': 'Istraživač sire',
  'badge.seerah_explorer.desc': 'Položi majstorski izazov Grada sire.',
  'badge.akhlaq_champion.name': 'Šampion ahlaka',
  'badge.akhlaq_champion.desc': 'Položi majstorski izazov Bašče ahlaka.',
  'badge.arabic_beginner.name': 'Početnik arapskog',
  'badge.arabic_beginner.desc': 'Položi majstorski izazov Akademije arapskog.',
  'badge.knowledge_seeker.name': 'Tragač za znanjem',
  'badge.knowledge_seeker.desc': 'Tačno odgovori na 50 pitanja.',
  'badge.knowledge_master.name': 'Majstor znanja',
  'badge.knowledge_master.desc': 'Savladaj svih osam oblasti.',
  'celebrate.levelTitle': 'Novi nivo!',
  'celebrate.levelBody': 'Tvoj junak je dostigao nivo {level} – snagom znanja.',

  'settings.title': 'Postavke',
  'settings.general': 'Općenito',
  'settings.language': 'Jezik',
  'settings.sound': 'Zvukovi',
  'settings.haptics': 'Vibracija',
  'settings.narration': 'Čitaj lekcije naglas',
  'settings.narrationDesc': 'Koristi glas tvog uređaja. Neobavezno.',
  'settings.accessibility': 'Pristupačnost',
  'settings.largeText': 'Veći tekst',
  'settings.highContrast': 'Visoki kontrast',
  'settings.reducedMotion': 'Smanji animacije',
  'settings.info': 'Informacije',
  'settings.about': 'O aplikaciji',
  'settings.privacy': 'Privatnost',
  'settings.sources': 'Izvori',
  'settings.data': 'Podaci',
  'settings.reset': 'Poništi napredak',
  'settings.resetDesc': 'Briše junaka, XP, dostignuća i napredak na ovom uređaju.',
  'settings.resetTitle': 'Poništiti sav napredak?',
  'settings.resetBody': 'Ovo se ne može vratiti.',
  'settings.resetConfirm': 'Da, poništi',
  'settings.version': 'Verzija {version}',

  'about.title': 'O aplikaciji',
  'about.p1': 'Knowledge RPG je besplatna islamska igra učenja: tvoj junak raste samo stvarnim učenjem – lekcijama, vježbama, testovima i ponavljanjem.',
  'about.p2': 'Bez reklama, kupovina, pretplata i bez plaćanja za prednost. Sve radi bez interneta.',
  'about.p3': 'Aplikacija je obrazovna i ne daje fetve. Gdje učenjaci imaju različita mišljenja, ona to i kaže. Za vjerska pitanja obrati se kvalifikovanom učenjaku.',
  'privacy.title': 'Privatnost',
  'privacy.p1': 'Lični podaci se ne prikupljaju, ne šalju i ne prodaju. Nema reklama, analitike ni praćenja, a aplikacija ne koristi internet.',
  'privacy.p2': 'Tvoj junak i napredak čuvaju se samo na ovom uređaju. „Poništi napredak“ ih briše.',
  'sources.title': 'Izvori',
  'sources.p1': 'Sadržaj se zasniva na Kur\'anu (navodi sura:ajet), zbirkama hadisa Sahih el-Buhari, Sahih Muslim, Sunen Ebu Davud i Džami’ et-Tirmizi, siri Ibn Hišama i priznatim djelima islamske historije.',
  'sources.p2': 'Svaka jedinica navodi svoje izvore. Nijedan ajet, hadis, kazivanje ni propis nije izmišljen, a poslanici se nikada ne prikazuju.',

  'error.title': 'Nešto nije u redu',
  'error.body': 'Tvoj napredak je siguran. Pokušaj ponovo.',
  'notFound.title': 'Stranica nije pronađena',
  'notFound.home': 'Na početnu',

  'a11y.avatar': 'Tvoj junak',
  'a11y.back': 'Nazad',
  'a11y.close': 'Zatvori',
  'a11y.card': 'Karta {index}',
  'a11y.hiddenCard': 'Skrivena karta {index}',
  'a11y.correct': 'tačno',
  'a11y.incorrect': 'netačno',
  'a11y.selected': 'odabrano',
  'a11y.progress': 'Napredak {percent} posto',
  'a11y.speak': 'Pusti izgovor',
  'a11y.stars': '{count} od 3 zvjezdice',
  'a11y.xpBar': '{xp} od {total} XP do sljedećeg nivoa',
};

export default bs;
