import type { Dictionary } from './en';

const de: Dictionary = {
  'app.name': 'Knowledge RPG',

  'common.continue': 'Weiter',
  'common.back': 'Zurück',
  'common.cancel': 'Abbrechen',
  'common.start': 'Starten',
  'common.done': 'Fertig',
  'common.check': 'Prüfen',
  'common.retry': 'Nochmal versuchen',
  'common.locked': 'Gesperrt',
  'common.level': 'Stufe {level}',
  'common.sources': 'Quellen',
  'common.scholarsDiffer': 'Gelehrte sind sich uneinig',
  'common.save': 'Speichern',

  'tabs.home': 'Start',
  'tabs.map': 'Karte',
  'tabs.quests': 'Quests',
  'tabs.profile': 'Held',

  'onboarding.welcome.title': 'Knowledge RPG',
  'onboarding.welcome.body': 'Dein Held wird durch echtes Wissen stärker. Lernen, antworten, verstehen – und aufsteigen.',
  'onboarding.language': 'Wähle deine Sprache',
  'onboarding.hero': 'Erstelle deinen Helden',
  'onboarding.name': 'Name deines Helden',
  'onboarding.namePlaceholder': 'Name',
  'onboarding.nameError': 'Bitte gib einen Namen ein (1–20 Zeichen).',
  'onboarding.loopTitle': 'So wächst du',
  'onboarding.loop': 'Lernen → Antworten → Verstehen → XP verdienen → Aufsteigen → Freischalten → Wiederholen',
  'onboarding.start': 'Abenteuer beginnen',
  'onboarding.next': 'Weiter',
  'onboarding.step': 'Schritt {current} von {total}',

  'character.title': 'Dein Held',
  'character.skin': 'Hautton',
  'character.hair': 'Haare',
  'character.hairColor': 'Haarfarbe',
  'character.headwear': 'Kopfbedeckung',
  'character.outfit': 'Kleidung',
  'character.outfitColor': 'Kleidungsfarbe',
  'character.accessory': 'Accessoire',
  'character.option': '{group}: {value}',
  'character.hair.short': 'Kurz',
  'character.hair.curly': 'Lockig',
  'character.hair.long': 'Lang',
  'character.hair.buzz': 'Kurzhaar',
  'character.hair.bun': 'Dutt',
  'character.headwear.none': 'Keine',
  'character.headwear.kufi': 'Kufi',
  'character.headwear.hijab': 'Hidschab',
  'character.headwear.cap': 'Kappe',
  'character.outfit.thobe': 'Thobe',
  'character.outfit.hoodie': 'Kapuzenpulli',
  'character.outfit.jacket': 'Jacke',
  'character.outfit.abaya': 'Abaya',
  'character.accessory.none': 'Keins',
  'character.accessory.glasses': 'Brille',
  'character.accessory.backpack': 'Rucksack',
  'character.accessory.scarf': 'Schal',
  'character.accessory.lantern': 'Laterne',

  'streak.label': 'Lernserie',
  'streak.days': '{count} Tage',
  'streak.day': '{count} Tag',
  'streak.today': 'Du hast heute gelernt',
  'streak.notToday': 'Schließe eine Lektion, Wiederholung oder Herausforderung ab, um deine Serie fortzusetzen',
  'streak.note': 'Nur sinnvolles Lernen zählt. Mach Pausen, wann immer du sie brauchst – Lernen ist kein Wettrennen.',

  'home.greeting': 'As-salamu alaikum, {name}!',
  'home.continue': 'Weiterlernen',
  'home.allDone': 'Alle Einheiten geschafft – versuche die Meister-Herausforderungen oder wiederhole.',
  'home.daily': 'Tägliche Herausforderung',
  'home.dailyDone': 'Heute geschafft – morgen gibt es eine neue.',
  'home.quests': 'Heutige Quests',
  'home.review': 'Versuchen wir es noch einmal',
  'home.reviewCount': 'Fällige Fragen: {count}',
  'home.reviewNone': 'Gerade nichts zu wiederholen',
  'home.stats': 'Wissenswerte',

  'map.title': 'Weltkarte',
  'map.subtitle': 'Jeder Ort ist ein Wissensgebiet. Schließe Einheiten ab, um den nächsten zu öffnen.',
  'map.locked': 'Schließe {count} Einheiten in „{area}“ ab, um es zu öffnen',
  'map.mastered': 'Gemeistert',

  'area.units': 'Lerneinheiten',
  'area.master': 'Meister-Herausforderung',
  'area.masterBody': '{count} Fragen aus diesem Gebiet. Du brauchst {percent} %, um zu bestehen.',
  'area.masterLocked': 'Schließe zuerst alle Einheiten dieses Gebiets ab.',
  'area.masterPassed': 'Bestanden · beste {score} %',
  'area.knowledge': 'Wissen: {percent} %',
  'area.unitLocked': 'Schließe zuerst die vorherige Einheit ab',
  'area.difficulty': 'Schwierigkeit {level}/3',
  'area.notFound': 'Dieses Gebiet wurde nicht gefunden.',

  'unit.learn': 'Lernen',
  'unit.practice': 'Üben',
  'unit.test': 'Test',
  'unit.explanation': 'Warum es wichtig ist',
  'unit.readAloud': 'Vorlesen',
  'unit.doneReading': 'Verstanden – üben',
  'unit.startTest': 'Test starten',
  'unit.finish': 'Belohnung abholen',
  'unit.notFound': 'Diese Einheit wurde nicht gefunden.',
  'unit.locked': 'Diese Einheit ist noch gesperrt.',
  'unit.exitTitle': 'Einheit verlassen?',
  'unit.exitBody': 'Deine bisherigen Antworten zählen nicht als abgeschlossene Einheit.',
  'unit.exit': 'Verlassen',
  'unit.stay': 'Bleiben',

  'player.correct': 'Richtig!',
  'player.notQuite': 'Nicht ganz',
  'player.correctAnswer': 'Richtige Antwort: {answer}',
  'player.addedToReview': 'Wir versuchen das später noch einmal.',
  'player.label.practice': 'Übung – ohne Wertung',
  'player.label.test': 'Test',
  'player.label.master': 'Meister-Herausforderung',
  'player.label.review': 'Versuchen wir es noch einmal',
  'player.label.daily': 'Tägliche Herausforderung',

  'q.true': 'Richtig',
  'q.false': 'Falsch',
  'q.ordering.hint': 'Tippe die Einträge in der richtigen Reihenfolge an.',
  'q.ordering.reset': 'Neu beginnen',
  'q.matching.hint': 'Tippe links einen Eintrag an, dann seinen Partner rechts.',
  'q.matching.mistakes': 'Fehler: {count}',
  'q.memory.hint': 'Decke zwei Karten auf, um ein Paar zu finden.',
  'q.memory.moves': 'Züge: {count}',
  'q.categorize.hint': 'Tippe einen Eintrag an, dann die Gruppe, zu der er gehört. Tippe einen platzierten Eintrag, um ihn zurückzulegen.',
  'q.scenario.title': 'Was würdest du tun?',

  'reward.title': 'Einheit geschafft!',
  'reward.score': '{correct} von {total} richtig',
  'reward.xp': '+{xp} XP',
  'reward.noXp': 'Die XP hast du hier schon verdient – erneutes Üben hilft dir trotzdem beim Merken.',
  'reward.newBadge': 'Neuer Erfolg!',
  'reward.next': 'Nächste Einheit',
  'reward.area': 'Zurück zum Gebiet',

  'master.title': 'Meister-Herausforderung',
  'master.intro': '{count} Fragen über {area}. Erreiche {percent} %, um dieses Gebiet zu meistern. Es ist eine Wissens-Herausforderung – kein Kampf, nur Verstehen.',
  'master.start': 'Herausforderung beginnen',
  'master.passedTitle': 'Gebiet gemeistert!',
  'master.passedBody': 'Du hast {score} % erreicht. Dein Wissen über {area} ist gewachsen.',
  'master.failedTitle': 'Noch nicht – und das ist in Ordnung',
  'master.failedBody': 'Du hast {score} % erreicht ({percent} % nötig). Wiederhole die Themen unten und versuche es dann erneut.',
  'master.weakTopics': 'Themen zum Wiederholen',
  'master.review': 'Jetzt wiederholen',
  'master.retry': 'Nochmal versuchen',

  'quests.title': 'Quest-Buch',
  'quests.subtitle': 'Ein paar kleine Quests pro Tag. Keine Timer, kein Druck.',
  'quests.daily': 'Schließe die heutige Herausforderung ab',
  'quests.learning': 'Schließe die Einheit „{title}“ ab',
  'quests.knowledge': 'Beantworte {count} Fragen zu {area} richtig',
  'quests.review': 'Wiederhole {count} Fragen, die du verpasst hast',
  'quests.challenge': 'Bestehe die Meister-Herausforderung von {area}',
  'quests.kind.daily': 'Tägliche Quest',
  'quests.kind.learning': 'Lern-Quest',
  'quests.kind.knowledge': 'Wissens-Quest',
  'quests.kind.review': 'Wiederholungs-Quest',
  'quests.kind.challenge': 'Herausforderungs-Quest',
  'quests.done': 'Erledigt',
  'quests.achievements': 'Erfolge',

  'review.title': 'Versuchen wir es noch einmal',
  'review.intro': 'Verpasste Fragen kommen nach einiger Zeit wieder – schwierige Themen zuerst.',
  'review.start': 'Starten ({count})',
  'review.emptyTitle': 'Gerade nichts fällig',
  'review.emptyBody': 'Verpasste Fragen kommen nach einer Weile hierher zurück.',
  'review.next': 'Nächste Wiederholung: {date}',
  'review.doneTitle': 'Wiederholung geschafft',
  'review.doneBody': 'Du hast dir {correct} von {total} gemerkt.',

  'daily.title': 'Tägliche Herausforderung',
  'daily.kind.question': 'Frage',
  'daily.kind.scenario': 'Szenario',
  'daily.kind.miniGame': 'Minispiel',
  'daily.kind.memory': 'Memory',
  'daily.kind.review': 'Wiederholung',
  'daily.doneTitle': 'Tägliche Herausforderung geschafft!',
  'daily.already': 'Die heutige Herausforderung hast du schon geschafft. Bis morgen!',

  'profile.title': 'Dein Held',
  'profile.edit': 'Held bearbeiten',
  'profile.xpToNext': 'Noch {xp} XP bis Stufe {level}',
  'profile.knowledgeMap': 'Wissenskarte',
  'profile.knowledgeNote': 'Anteil der Inhalte jedes Gebiets, die du richtig beantwortet hast und gerade nicht wiederholen musst – gemessen wird gelerntes Wissen, nicht Glaube.',
  'profile.stats': 'Statistik',
  'profile.settings': 'Einstellungen',
  'stats.units': 'Abgeschlossene Einheiten',
  'stats.masters': 'Gemeisterte Gebiete',
  'stats.answers': 'Richtige Antworten',
  'stats.accuracy': 'Genauigkeit',
  'stats.longest': 'Längste Serie',
  'stats.reviews': 'Gemerkte Wiederholungen',
  'badges.locked': 'Noch nicht verdient',
  'badges.earnedOn': 'Verdient am {date}',
  'badge.first_lesson.name': 'Erste Lektion',
  'badge.first_lesson.desc': 'Schließe deine erste Einheit ab.',
  'badge.first_perfect_quiz.name': 'Erstes perfektes Quiz',
  'badge.first_perfect_quiz.desc': 'Beantworte alle Testfragen einer Einheit richtig.',
  'badge.learner_7.name': '7-Tage-Lerner',
  'badge.learner_7.desc': 'Lerne an 7 Tagen hintereinander.',
  'badge.learner_30.name': '30-Tage-Lerner',
  'badge.learner_30.desc': 'Lerne an 30 Tagen hintereinander.',
  'badge.salah_scholar.name': 'Gebets-Gelehrter',
  'badge.salah_scholar.desc': 'Bestehe die Meister-Herausforderung im Tal des Gebets.',
  'badge.quran_explorer.name': 'Koran-Entdecker',
  'badge.quran_explorer.desc': 'Bestehe die Meister-Herausforderung der Koran-Bibliothek.',
  'badge.seerah_explorer.name': 'Sira-Entdecker',
  'badge.seerah_explorer.desc': 'Bestehe die Meister-Herausforderung der Stadt der Sira.',
  'badge.akhlaq_champion.name': 'Charakter-Champion',
  'badge.akhlaq_champion.desc': 'Bestehe die Meister-Herausforderung im Garten des Charakters.',
  'badge.arabic_beginner.name': 'Arabisch-Anfänger',
  'badge.arabic_beginner.desc': 'Bestehe die Meister-Herausforderung der Arabisch-Akademie.',
  'badge.knowledge_seeker.name': 'Wissenssucher',
  'badge.knowledge_seeker.desc': 'Beantworte 50 Fragen richtig.',
  'badge.knowledge_master.name': 'Wissensmeister',
  'badge.knowledge_master.desc': 'Meistere alle acht Gebiete.',
  'celebrate.levelTitle': 'Aufgestiegen!',
  'celebrate.levelBody': 'Dein Held hat Stufe {level} erreicht – angetrieben von Wissen.',

  'settings.title': 'Einstellungen',
  'settings.general': 'Allgemein',
  'settings.language': 'Sprache',
  'settings.sound': 'UI-Töne',
  'settings.haptics': 'Vibration',
  'settings.narration': 'Lektionen vorlesen',
  'settings.narrationDesc': 'Nutzt die Stimme deines Geräts. Optional.',
  'settings.accessibility': 'Barrierefreiheit',
  'settings.largeText': 'Größere Schrift',
  'settings.highContrast': 'Hoher Kontrast',
  'settings.reducedMotion': 'Bewegung reduzieren',
  'settings.info': 'Informationen',
  'settings.about': 'Über die App',
  'settings.privacy': 'Datenschutz',
  'settings.sources': 'Quellen',
  'settings.data': 'Daten',
  'settings.reset': 'Fortschritt zurücksetzen',
  'settings.resetDesc': 'Löscht Held, XP, Erfolge und Fortschritt auf diesem Gerät.',
  'settings.resetTitle': 'Gesamten Fortschritt zurücksetzen?',
  'settings.resetBody': 'Das kann nicht rückgängig gemacht werden.',
  'settings.resetConfirm': 'Ja, zurücksetzen',
  'settings.version': 'Version {version}',

  'about.title': 'Über die App',
  'about.p1': 'Knowledge RPG ist ein kostenloses islamisches Lernspiel: Dein Held wächst nur durch echtes Lernen – Lektionen, Übungen, Tests und Wiederholung.',
  'about.p2': 'Keine Werbung, keine Käufe, keine Abos und nichts Pay-to-win. Alles funktioniert offline.',
  'about.p3': 'Die App ist ein Lernangebot und erteilt keine Fatwas. Wo Gelehrte unterschiedliche Ansichten haben, sagt sie das. Bei religiösen Fragen wende dich an einen qualifizierten Gelehrten.',
  'privacy.title': 'Datenschutz',
  'privacy.p1': 'Es werden keine persönlichen Daten gesammelt, gesendet oder verkauft. Es gibt keine Werbung, Analyse oder Tracking, und die App nutzt kein Internet.',
  'privacy.p2': 'Dein Held und dein Fortschritt werden nur auf diesem Gerät gespeichert. „Fortschritt zurücksetzen“ löscht sie.',
  'sources.title': 'Quellen',
  'sources.p1': 'Die Inhalte beruhen auf dem Koran (Sure:Vers-Angaben), den Hadith-Sammlungen Sahih al-Buchari, Sahih Muslim, Sunan Abi Dawud und Dschami’ at-Tirmidhi, der Sira von Ibn Hischam und anerkannten Werken der islamischen Geschichte.',
  'sources.p2': 'Jede Einheit nennt ihre Belege. Es werden keine Koranverse, Hadithe, Geschichten oder Urteile erfunden, und Propheten werden nie dargestellt.',

  'error.title': 'Etwas ist schiefgelaufen',
  'error.body': 'Dein Fortschritt ist sicher. Bitte versuche es erneut.',
  'notFound.title': 'Seite nicht gefunden',
  'notFound.home': 'Zur Startseite',

  'a11y.avatar': 'Dein Held',
  'a11y.back': 'Zurück',
  'a11y.close': 'Schließen',
  'a11y.card': 'Karte {index}',
  'a11y.hiddenCard': 'Verdeckte Karte {index}',
  'a11y.correct': 'richtig',
  'a11y.incorrect': 'falsch',
  'a11y.selected': 'ausgewählt',
  'a11y.progress': 'Fortschritt {percent} Prozent',
  'a11y.speak': 'Aussprache abspielen',
  'a11y.stars': '{count} von 3 Sternen',
  'a11y.xpBar': '{xp} von {total} XP bis zur nächsten Stufe',
};

export default de;
