const en = {
  'app.name': 'Knowledge RPG',

  'common.continue': 'Continue',
  'common.back': 'Back',
  'common.cancel': 'Cancel',
  'common.start': 'Start',
  'common.done': 'Done',
  'common.check': 'Check',
  'common.retry': 'Try again',
  'common.locked': 'Locked',
  'common.level': 'Level {level}',
  'common.sources': 'Sources',
  'common.scholarsDiffer': 'Scholars differ',
  'common.save': 'Save',

  'tabs.home': 'Home',
  'tabs.map': 'Map',
  'tabs.quests': 'Quests',
  'tabs.profile': 'Hero',

  'onboarding.welcome.title': 'Knowledge RPG',
  'onboarding.welcome.body': 'Your hero grows stronger with real knowledge. Learn, answer, understand – and level up.',
  'onboarding.language': 'Choose your language',
  'onboarding.hero': 'Create your hero',
  'onboarding.name': 'Your hero’s name',
  'onboarding.namePlaceholder': 'Name',
  'onboarding.nameError': 'Please enter a name (1–20 characters).',
  'onboarding.loopTitle': 'How you grow',
  'onboarding.loop': 'Learn → Answer → Understand → Earn XP → Level up → Unlock → Review',
  'onboarding.start': 'Begin the adventure',
  'onboarding.next': 'Next',
  'onboarding.step': 'Step {current} of {total}',

  'character.title': 'Your hero',
  'character.skin': 'Skin tone',
  'character.hair': 'Hair',
  'character.hairColor': 'Hair colour',
  'character.headwear': 'Headwear',
  'character.outfit': 'Outfit',
  'character.outfitColor': 'Outfit colour',
  'character.accessory': 'Accessory',
  'character.option': '{group}: {value}',
  'character.hair.short': 'Short',
  'character.hair.curly': 'Curly',
  'character.hair.long': 'Long',
  'character.hair.buzz': 'Buzz cut',
  'character.hair.bun': 'Bun',
  'character.headwear.none': 'None',
  'character.headwear.kufi': 'Kufi',
  'character.headwear.hijab': 'Hijab',
  'character.headwear.cap': 'Cap',
  'character.outfit.thobe': 'Thobe',
  'character.outfit.hoodie': 'Hoodie',
  'character.outfit.jacket': 'Jacket',
  'character.outfit.abaya': 'Abaya',
  'character.accessory.none': 'None',
  'character.accessory.glasses': 'Glasses',
  'character.accessory.backpack': 'Backpack',
  'character.accessory.scarf': 'Scarf',
  'character.accessory.lantern': 'Lantern',

  'streak.label': 'Learning streak',
  'streak.days': '{count} days',
  'streak.day': '{count} day',
  'streak.today': 'You learned today',
  'streak.notToday': 'Finish a lesson, review or challenge to continue your streak',
  'streak.note': 'Only meaningful learning counts. Take breaks whenever you need – learning is not a race.',

  'home.greeting': 'As-salamu alaykum, {name}!',
  'home.continue': 'Continue learning',
  'home.allDone': 'All units completed – try the Master Challenges or review.',
  'home.daily': 'Daily challenge',
  'home.dailyDone': 'Completed today – a new one tomorrow.',
  'home.quests': 'Today’s quests',
  'home.review': 'Let’s try this again',
  'home.reviewCount': 'Questions due: {count}',
  'home.reviewNone': 'Nothing to review right now',
  'home.stats': 'Knowledge stats',

  'map.title': 'World Map',
  'map.subtitle': 'Each place is a field of knowledge. Complete units to open the next one.',
  'map.locked': 'Complete {count} units in “{area}” to unlock',
  'map.mastered': 'Mastered',

  'area.units': 'Learning units',
  'area.master': 'Master Challenge',
  'area.masterBody': '{count} questions from this area. You need {percent}% to pass.',
  'area.masterLocked': 'Complete all units of this area first.',
  'area.masterPassed': 'Passed · best {score}%',
  'area.knowledge': 'Knowledge: {percent}%',
  'area.unitLocked': 'Finish the previous unit first',
  'area.difficulty': 'Difficulty {level}/3',
  'area.notFound': 'This area could not be found.',

  'unit.learn': 'Learn',
  'unit.practice': 'Practice',
  'unit.test': 'Test',
  'unit.explanation': 'Why it matters',
  'unit.readAloud': 'Read aloud',
  'unit.doneReading': 'I understood – practice',
  'unit.startTest': 'Start the test',
  'unit.finish': 'Collect reward',
  'unit.notFound': 'This unit could not be found.',
  'unit.locked': 'This unit is still locked.',
  'unit.exitTitle': 'Leave this unit?',
  'unit.exitBody': 'Your answers so far will not count as a finished unit.',
  'unit.exit': 'Leave',
  'unit.stay': 'Stay',

  'player.correct': 'Correct!',
  'player.notQuite': 'Not quite',
  'player.correctAnswer': 'Correct answer: {answer}',
  'player.addedToReview': 'We will try this again later.',
  'player.label.practice': 'Practice – not scored',
  'player.label.test': 'Test',
  'player.label.master': 'Master Challenge',
  'player.label.review': 'Let’s try this again',
  'player.label.daily': 'Daily challenge',

  'q.true': 'True',
  'q.false': 'False',
  'q.ordering.hint': 'Tap the items in the right order.',
  'q.ordering.reset': 'Start over',
  'q.matching.hint': 'Tap an item on the left, then its partner on the right.',
  'q.matching.mistakes': 'Mistakes: {count}',
  'q.memory.hint': 'Flip two cards to find a matching pair.',
  'q.memory.moves': 'Moves: {count}',
  'q.categorize.hint': 'Tap an item, then the group it belongs to. Tap a placed item to move it back.',
  'q.scenario.title': 'What would you do?',

  'reward.title': 'Unit complete!',
  'reward.score': '{correct} of {total} correct',
  'reward.xp': '+{xp} XP',
  'reward.noXp': 'You already earned the XP here – practising again still helps you remember.',
  'reward.newBadge': 'New achievement!',
  'reward.next': 'Next unit',
  'reward.area': 'Back to the area',

  'master.title': 'Master Challenge',
  'master.intro': '{count} questions about {area}. Reach {percent}% to master this area. This is a knowledge challenge – no fighting, just understanding.',
  'master.start': 'Begin the challenge',
  'master.passedTitle': 'Area mastered!',
  'master.passedBody': 'You scored {score}%. Your knowledge of {area} has grown.',
  'master.failedTitle': 'Not yet – and that’s okay',
  'master.failedBody': 'You scored {score}% ({percent}% needed). Review the topics below, then try again.',
  'master.weakTopics': 'Topics to review',
  'master.review': 'Review now',
  'master.retry': 'Try again',

  'quests.title': 'Quest Log',
  'quests.subtitle': 'A few small quests each day. No timers, no pressure.',
  'quests.daily': 'Complete today’s daily challenge',
  'quests.learning': 'Complete the unit “{title}”',
  'quests.knowledge': 'Answer {count} {area} questions correctly',
  'quests.review': 'Review {count} questions you previously missed',
  'quests.challenge': 'Pass the Master Challenge of {area}',
  'quests.kind.daily': 'Daily quest',
  'quests.kind.learning': 'Learning quest',
  'quests.kind.knowledge': 'Knowledge quest',
  'quests.kind.review': 'Review quest',
  'quests.kind.challenge': 'Challenge quest',
  'quests.done': 'Done',
  'quests.achievements': 'Achievements',

  'review.title': 'Let’s try this again',
  'review.intro': 'Questions you missed come back after some time – topics you struggle with come first.',
  'review.start': 'Start ({count})',
  'review.emptyTitle': 'Nothing due right now',
  'review.emptyBody': 'Missed questions return here after a while.',
  'review.next': 'Next review: {date}',
  'review.doneTitle': 'Review complete',
  'review.doneBody': 'You remembered {correct} of {total}.',

  'daily.title': 'Daily challenge',
  'daily.kind.question': 'Question',
  'daily.kind.scenario': 'Scenario',
  'daily.kind.miniGame': 'Mini game',
  'daily.kind.memory': 'Memory',
  'daily.kind.review': 'Review',
  'daily.doneTitle': 'Daily challenge complete!',
  'daily.already': 'You already completed today’s challenge. See you tomorrow!',

  'profile.title': 'Your hero',
  'profile.edit': 'Edit hero',
  'profile.xpToNext': '{xp} XP to level {level}',
  'profile.knowledgeMap': 'Knowledge map',
  'profile.knowledgeNote': 'Percent of each area’s content you have answered correctly and not currently need to review – it measures learned content, not faith.',
  'profile.stats': 'Statistics',
  'profile.settings': 'Settings',
  'stats.units': 'Units completed',
  'stats.masters': 'Areas mastered',
  'stats.answers': 'Correct answers',
  'stats.accuracy': 'Accuracy',
  'stats.longest': 'Longest streak',
  'stats.reviews': 'Reviews remembered',
  'badges.locked': 'Not earned yet',
  'badges.earnedOn': 'Earned on {date}',
  'badge.first_lesson.name': 'First Lesson',
  'badge.first_lesson.desc': 'Complete your first unit.',
  'badge.first_perfect_quiz.name': 'First Perfect Quiz',
  'badge.first_perfect_quiz.desc': 'Answer every test question of a unit correctly.',
  'badge.learner_7.name': '7 Day Learner',
  'badge.learner_7.desc': 'Learn on 7 days in a row.',
  'badge.learner_30.name': '30 Day Learner',
  'badge.learner_30.desc': 'Learn on 30 days in a row.',
  'badge.salah_scholar.name': 'Salah Scholar',
  'badge.salah_scholar.desc': 'Pass the Master Challenge of Salah Valley.',
  'badge.quran_explorer.name': 'Quran Explorer',
  'badge.quran_explorer.desc': 'Pass the Master Challenge of the Quran Library.',
  'badge.seerah_explorer.name': 'Seerah Explorer',
  'badge.seerah_explorer.desc': 'Pass the Master Challenge of Seerah City.',
  'badge.akhlaq_champion.name': 'Akhlaq Champion',
  'badge.akhlaq_champion.desc': 'Pass the Master Challenge of the Akhlaq Garden.',
  'badge.arabic_beginner.name': 'Arabic Beginner',
  'badge.arabic_beginner.desc': 'Pass the Master Challenge of the Arabic Academy.',
  'badge.knowledge_seeker.name': 'Knowledge Seeker',
  'badge.knowledge_seeker.desc': 'Answer 50 questions correctly.',
  'badge.knowledge_master.name': 'Knowledge Master',
  'badge.knowledge_master.desc': 'Master all eight areas.',
  'celebrate.levelTitle': 'Level up!',
  'celebrate.levelBody': 'Your hero reached level {level} – powered by knowledge.',

  'settings.title': 'Settings',
  'settings.general': 'General',
  'settings.language': 'Language',
  'settings.sound': 'UI sounds',
  'settings.haptics': 'Vibration',
  'settings.narration': 'Read lessons aloud',
  'settings.narrationDesc': 'Uses your device’s voice. Optional.',
  'settings.accessibility': 'Accessibility',
  'settings.largeText': 'Larger text',
  'settings.highContrast': 'High contrast',
  'settings.reducedMotion': 'Reduce motion',
  'settings.info': 'Information',
  'settings.about': 'About',
  'settings.privacy': 'Privacy',
  'settings.sources': 'Sources',
  'settings.data': 'Data',
  'settings.reset': 'Reset progress',
  'settings.resetDesc': 'Deletes your hero, XP, achievements and progress on this device.',
  'settings.resetTitle': 'Reset all progress?',
  'settings.resetBody': 'This cannot be undone.',
  'settings.resetConfirm': 'Yes, reset',
  'settings.version': 'Version {version}',

  'about.title': 'About',
  'about.p1': 'Knowledge RPG is a free Islamic learning game: your hero grows only through real learning – lessons, practice, tests and review.',
  'about.p2': 'No ads, no purchases, no subscriptions and nothing pay-to-win. Everything works offline.',
  'about.p3': 'The app is educational and does not give fatwas. Where scholars hold different views, it says so. For religious questions, ask a qualified scholar.',
  'privacy.title': 'Privacy',
  'privacy.p1': 'No personal data is collected, sent or sold. There are no ads, analytics or tracking, and the app does not use the internet.',
  'privacy.p2': 'Your hero and progress are stored only on this device. “Reset progress” deletes them.',
  'sources.title': 'Sources',
  'sources.p1': 'Content is based on the Quran (surah:ayah references), the hadith collections Sahih al-Bukhari, Sahih Muslim, Sunan Abi Dawud and Jami’ at-Tirmidhi, the Seerah of Ibn Hisham, and established works of Islamic history.',
  'sources.p2': 'Every unit lists its references. No Quran verses, hadith, stories or rulings are invented, and prophets are never depicted.',

  'error.title': 'Something went wrong',
  'error.body': 'Your progress is safe. Please try again.',
  'notFound.title': 'Page not found',
  'notFound.home': 'Go home',

  'a11y.avatar': 'Your hero',
  'a11y.back': 'Go back',
  'a11y.close': 'Close',
  'a11y.card': 'Card {index}',
  'a11y.hiddenCard': 'Hidden card {index}',
  'a11y.correct': 'correct',
  'a11y.incorrect': 'incorrect',
  'a11y.selected': 'selected',
  'a11y.progress': 'Progress {percent} percent',
  'a11y.speak': 'Play pronunciation',
  'a11y.stars': '{count} of 3 stars',
  'a11y.xpBar': '{xp} of {total} XP towards the next level',
} as const;

export type TranslationKey = keyof typeof en;
export type Dictionary = Record<TranslationKey, string>;

export default en as Dictionary;
